#:schema node_modules/wrangler/config-schema.json
name = "app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/.output"

[vars]
# NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
